baseURL: https://jerome-bouvier.github.io/
languageCode: fr
title: jeromeboubou.cool
theme: "PaperMod"
params:
    homeInfoParams:
        Title: Hi there wave
        Content: I'm Jerome
outputs:
    home:
        - HTML
        - RSS
        - JSON