baseURL: https://jerome-bouvier.github.io/
languageCode: fr
title: jeromeboubou.cool
theme: "PaperMod"
params:
    homeInfoParams:
        Title: Hi there wave
        Content: I'm Jerome

    socialIcons: # optional
        - name: "github"
            url: "https://github.com/jerome-bouvier/"
        - name: "instagram"
            url: "https://www.instagram.com/poneyponey/"
        - name: "twitter"
            url: "https://twitter.com/jeromm/"
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary